carrier:
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

 joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  publish_rate: 50
  joints:
   - carrier_base_wheel_R_joint
   - child_base_wheel_R_joint
   - child_base_wheel_L_joint
  gains:
   carrier_base_wheel_R_joint: {p: 10.0, i: 0, d: 0}
   child_base_wheel_R_joint: {p: 10.0, i: 0, d: 0}
   child_base_wheel_L_joint: {p: 10.0, i: 0, d: 0}

# carrier_wheel_velocity_controller:
#  type: effort_controllers/JointVelocityController
#  publish_rate: 50
#  joint: carrier_base_wheel_R_joint
#  pid: {p: 10.0, i: 0, d: 0}

# child_wheel_R_velocity_controller:
#  type: effort_controllers/JointVelocityController
#  publish_rate: 50
#  joint: child_base_wheel_R_joint
#  pid: {p: 10.0, i: 0, d: 0}

# child_wheel_L_velocity_controller:
#  type: effort_controllers/JointVelocityController
#  publish_rate: 50
#  joint: child_base_wheel_L_joint
#  pid: {p: 10.0, i: 0, d: 0}
